package com.pilaf.warhammer.combat;

public enum Race {
    EMPIRE, HIGH_ELVES, WOOD_ELVES, DWARFS, CHAOS, NORSKA, GREENSKINS, VAMPIRES, VAMPIRE_COAST, BRETONIA, BEASTMAN, TOMB_KINGS, SKAVEN, DARK_ELVES, LIZARDMAN
}
