package com.pilaf.warhammer.combat;

public enum Skills {

    CAUSE_FEAR, CAUSE_TERROR, MAGICAL_ATTACK, FIRE_ATTACK, IMMUNE_TO_PSYCHOLOGY, CHARGE_DEFENCE_AGAINST_LARGE,
    CHARGE_DEFENCE_EXPERT, UNBREAKABLE, UNDEAD, BRONZE_SHIELD, SILVER_SHIELD, GOLD_SHIELD, FRENZY,
    MURDEROUS_MASTERY,  MADNESS_OF_KHAINE, PRIMAL_INSTINCTS, SOUL_DECAY, POISON_ATTACK, PRIMAL_FRENZY, ENCOURAGE, DEATHBLOW, OPPORTUNIST_MURDERER, REGENERATION, RAMPAGE, CRAZY_SQUIQ, CLIN, PERFECT_VIGOUR, OVERWHELMING_ODOUR, MARTIAL_PROWES, MARTIAL_MASTERY, STRENTH_IN_NUMBERS, SCURRY_AWAY, WARP_QUAKE, WEAPING_BLADE, CONTAMINETED, PRIMAL_FURY, ROWDY, BLOODGREED, SHADOW_COIL, GUARDIANS_OF_THE_WILDWOOD, WOVEN_MIST, DISINTEGRATING, THE_FLAG_OF_BLOOD_KEED, REALM_OF_SOULS, CONSTRUCT;
}
