package com.pilaf.warhammer.combat;

public enum Skills {

    CAUSE_FEAR, CAUSE_TERROR, MAGICAL_ATTACK, FIRE_ATTACK, IMMUNE_TO_PSYCHOLOGY, CHARGE_DEFENCE_AGAINST_LARGE,
    CHARGE_DEFENCE_EXPERT, UNBREAKABLE, UNDEAD, BRONZE_SHIELD, SILVER_SHIELD, GOLD_SHIELD, FRENZY,
    MURDEROUS_MASTERY,  MADNESS_OF_KHAINE, PRIMAL_INSTINCTS, SOUL_DECAY, POISON_ATTACK, PRIMAL_FRENZY, ENCOURAGE, DEATHBLOW;
}
